version: '3.8'
services:
  web:
    image: ${DOCKERHUB_USERNAME:-yourusername}/myflask:latest
    environment:
      - FLASK_ENV=production
    expose:
      - "5000"           # 외부 노출은 nginx가 담당
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443" #443 포트 추가
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro       # Nginx 설정 파일
      - ./certbot/conf:/etc/letsencrypt    # 인증서 파일
      - ./certbot/www:/var/www/certbot     # certbot 웹루트
    restart: unless-stopped
    command: "/bin/sh -c 'nginx -g \"daemon off;\" & while :; do sleep 6h; nginx -s reload; done'"


  certbot:  
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh
    command: -c "while :; do certbot renew --webroot -w /var/www/certbot && echo 'renew check'; sleep 12h; done"
    restart: unless-stopped # 컨테이너가 죽으면 자동으로 재시작되도록 함 (필수!)
