name : CD - Build & push to Docker Hub
on:
  push:
    branches: [ main ]
    #태그(push) 이벤트 발생 시 실행
  tags: [ 'v*.*.*' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #docker hub에 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 이미지 빌드 및 태그 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/myflask:latest
            ${{ secrets.DOCKER_USERNAME }}/myflask:${{ github.sha }}
        
      #뒷정리 선택      
      - name : Logout from Docker Hub
        run: docker logout